[package]
name = "rockpaperscissors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.26.0"
ring = "0.16.20"
solana-sdk = "1.14.13"
